language: rust
sudo: required
install:
- wget https://www.libsdl.org/release/SDL2-2.0.4.tar.gz -O sdl2.tar.gz
- tar xzf sdl2.tar.gz
- pushd SDL2-2.0.4 && ./configure && make && sudo make install && popd
script:
- cargo build --verbose
- cargo test --verbose
- cargo build --features "use-sdl2" --verbose
- cargo test --verbose

env:
  global:
  - LD_LIBRARY_PATH: "/usr/local/lib"
