[package]

name = "uo-rust-libs"
version = "0.0.1"
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]

[features]
default = []
use-sdl2 = ["sdl2"]

[lib]

name = "uorustlibs"
path = "src/lib.rs"

[dependencies]
byteorder = "1.2"
image = "0.18"
sdl2 = { version = "0.29.0", optional = true }
